config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users

  # for admin
  namespace :admin do
    resources :categories
    resources :products
  end
  # for user
  resources :products, only: [] do
    get "/" => "products#index", on: :collection, as: :list
    get "/:id" => "products#show", on: :collection, as: :detail
  end

  resources :orders
  resources :order_products
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < AdminController
    before_action :set_category, only: %i[ show edit update destroy ]
    # GET /categories or /categories.json
    def index
      @categories = Category.all
      @category = Category.new
      @products = Product.all
    end

    # GET /categories/1 or /categories/1.json
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories or /categories.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to admin_categories_url, notice: "Category was successfully created." }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /categories/1 or /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to admin_categories_url, notice: "Category was successfully updated." }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /categories/1 or /categories/1.json
    def destroy
      @category.destroy

      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card my-4">
	<div class="card-body">
		<div class="container text-start">
			<strong>Name:</strong>
			<%= category.name %>
		</div>
	</div>
</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
	<% if category.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
			<ul>
				<% category.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="mb-3">
		<%= form.label :name, class: "form-label" %>
		<%= form.text_field :name, class: "form-control" %>
	</div>
	<div class="py-2">
		<%= form.submit class: "btn btn-primary" %>
	</div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "admin/categories/form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", admin_category_url(@category.id) %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
	<div class="row py-4">
		<div class="col">
			<h1>Categories</h1>
		</div>
		<div class="col text-end">
			<%= link_to "New category", new_admin_category_path, class: 'btn btn-primary' %>
		</div>
	</div>
	<div class="row py-4">
		<div class="col-4">
			<%= render 'form', category: @category %>
		</div>
		<div class="col-8">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">ID</th>
						<th scope="col">Name</th>
						<th scope="col">Created</th>
					</tr>
				</thead>
				<tbody>
					<% @categories.each do |category| %>
						<tr>
							<th scope="row"><%= category.id %></th>
							<td><%= category.name %></td>
							<td><%= category.created_at.strftime("%d/%m/%Y") %></td>
							<td class="d-inline-flex p-2">
								<%= link_to "Show", admin_category_url(category), class: 'btn btn-sm btn-info mb-1 mx-1' %>
								<%= link_to "Edit", edit_admin_category_path(category), class: 'btn btn-sm btn-warning mb-1 mx-1' %>
								<%= button_to "Destroy", admin_category_path(category), method: :delete, data: {turbo_confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger mb-1 mx-1' %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", admin_category_path(@category), method: :delete %>
</div>