config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users

  # for admin
  namespace :admin do
    resources :categories
    resources :products
  end
  # for user
  resources :products, only: [] do
    get "/" => "products#index", on: :collection, as: :list
    get "/:id" => "products#show", on: :collection, as: :detail
  end

  resources :orders
  resources :order_products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_rich_text :description
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  def self.search(params)
    if params[:q].present?
      # chi duoc includes moi quan he
      return includes(:category) 
               .where("LOWER(title) LIKE LOWER(?)", "%#{params[:q].to_s.squish}%")
               .order(id: :desc)
               .paginate(page: params[:page] || 1, per_page: 10)
    end

    includes(:category)
      .order(id: :desc)
      .paginate(page: params[:page] || 1, per_page: 10)
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
    
    # GET /products or /products.json
    def index
      @products = Product&.all
      @categories = Category&.all
      @category = Category.new
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_url, notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_url, notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy

      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :description, :category_id)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show ]

  # GET /products or /products.json
  def index
    @products = Product&.all
    @categories = Category&.all
  end

  # GET /products/1 or /products/1.json
  def show
    @products = Product.find(params[:id])
  end

  def choose
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :image, :description, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product]) do |form| %>
	<% if product.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
			<ul>
				<% product.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="container">
		<div>
			<%= form.label :name, class: 'form-label' %>
			<%= form.text_field :name, class: 'form-control', style: "width: 30rem;"%>
		</div>
		<div>
			<p><%= form.label :price, class: 'form-label' %></p>
			<%= form.number_field :price, style: "width: 18rem;" %>
		</div>
		<div class="field">
			<%= form.label :description, class: 'form-label' %>
			<%= form.rich_text_area :content %>
		</div>
		<div class="mt-3">
			<%= form.label :image, class: "form-label" %>
			<%= form.file_field :image %>
		</div>
		<div class="mt-3" style="width: 18rem;">
			<%= form.label :category_id, class: "form-label" %>
			<%= form.collection_select :category_id, Category.order(:name), :id, :name, {prompt: true}, {class: "form-control"} %>
		</div>
	</div>
	<div>
		<%= form.submit class: 'btn btn-primary mt-4'%>
	</div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
	<p>
		<strong>Name:</strong>
		<%= product.name %>
	</p>
	<p>
		<strong>Price:</strong>
		<%= product.price %>
	</p>
	<% if product.image.attached? %>
		<div>
			<%= image_tag product.image.variant(:thumb), class: "card-image-top" %>
		</div>
	<% end %>
	<p>
		<strong>Description:</strong>
		<%= product.description %>
	</p>
	<p>
		<strong>Category:</strong>
		<%= product.category_id %>
	</p>
</div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>
<%= render "admin/products/form", product: @product %>
<br>
<div>
	<%= link_to "Show this product", admin_product_path(@product) %> |
	<%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<div class="container">
	<div class="row py-4">
		<div class="col">
			<h1>Products</h1>
		</div>
		<div class="col text-end">
			<%= link_to "New product", new_admin_product_path, class: 'btn btn-primary' %>
		</div>
	</div>
	<div class="row">
		<div class="col-4">
			<h5>Categories</h5>
			<div class="list-group">
				<% @categories.each do |category| %>
					<a href="<%= admin_products_path(cid: category.id) %>" class="list-group-item list-group-item-action"><%= category.name %></a>
				<% end %>
			</div>
		</div>
		<div class="col-8">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">Products</h5>
					<div id="products">
						<% @products.each do |product| %>
							<%= render product %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render "admin/products/form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_admin_product_path(@product) %> |
  <%= link_to "Back to products", admin_products_path %>

  <%= button_to "Destroy this product", admin_product_path(@product), method: :delete %>
</div>